import pandas as pd
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
from prompts_json import  generate_episode

# Load the model and tokenizer for generating the episodes
MODEL_NAME = "meta-llama/Meta-Llama-3-8B-Instruct"
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, device_map="auto")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# Define the JSON schema for generating episodes
json_schema_episode = {
    "type": "object",
    "properties": {
        "Agent A": {"type": "array", "items": {"type": "string"}},
        "Agent B": {"type": "array", "items": {"type": "string"}},
    },
    "required": ["Agent A", "Agent B"]
}

# Function to extract episode data and generate episodes
def extract_and_generate_episodes(csv_file):
    # Load the CSV data into a pandas DataFrame
    df = pd.read_csv(csv_file)
    
    # Lists to store the generated episode data
    episode_agent_a_list = []
    episode_agent_b_list = []

    # Loop through each row in the CSV to extract the fields and generate episodes
    for index, row in df.iterrows():
        title = row['movie_scene.title']  # Movie scene title
        interaction_type = row['interaction_type']
        scenario_title = row['scenario.title']
        scenario_description = row['scenario.description']
        character1 = row['movie_scene.character1']
        character2 = row['movie_scene.character2']
        setting = row['movie_scene.setting']
        goals1 = row['scenario.goals1']
        goals2 = row['scenario.goals2']
        interaction = row['scenario.interaction']

        # Generate the episode using the extracted fields
        episode = generate_episode(
            title, title, interaction_type, scenario_title, scenario_description, 
            setting, interaction, character1, character2, goals1, goals2, 
            model, tokenizer, json_schema_episode, max_length=50
        )
        
        # Extract Agent A and Agent B data from the generated episode
        episode_agent_a = episode.get('Agent A', [])
        episode_agent_b = episode.get('Agent B', [])

        # Append the episode data to the corresponding lists
        episode_agent_a_list.append(episode_agent_a)
        episode_agent_b_list.append(episode_agent_b)

        print(f"Generated episode for row {index}: {episode}")

    # Add the generated episodes (Agent A and Agent B) as new columns in the original DataFrame
    df['episode.Agent A'] = episode_agent_a_list
    df['episode.Agent B'] = episode_agent_b_list

    # Save the updated DataFrame back to the same CSV file
    df.to_csv(csv_file, index=False)
    print("Episodes have been added to the CSV file.")

# Call the function and generate episodes, updating the CSV file in-place
csv_file = './scenes_scenario_validation_final.csv'  # Path to the CSV file generated by the previous script
extract_and_generate_episodes(csv_file)
